---
title: "The Mogwai Effect"
description: |
  Youtber's content matters
base_url: https://www.llorr-stats.com
preview: "https://dd.b.pvp.net/latest/set5/en_us/img/cards/05BC133T1-full.png"
author:
  - name: Valentino (Legna) Vazzoler
date: 09-30-2021
output:
 distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
    self_contained: false
citation: false
draft: FALSE
params:
  # prev:  "2021-09-22 21:00:00" #UTC tz / 'current' previous week start
  # start: "2021-09-01 21:00:00" #UTC tz / 'current' week start
  # end:   "2021-10-01 21:00:00" #UTC tz / 'current' week end
  start: "2021-10-20 21:00:00" #UTC tz / 2.18 <- Balance Patch
  end:   "2022-01-01 21:00:00" #UTC tz /
  # skip:  2800000  # ~ Patch 2.16
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = NA,
  R.options = list(width = 140,
                   digits.secs=6),
  dev.args = list(bg = 'transparent'), # make graphics with transparent background
  fig.align = 'center',
  fig.width=9,
  fig.height=6,
  engine.path = list(
    python = 'C:/anaconda/'   # -> use_python("C:/anaconda/")
  ),
  #'distill options
  layout="l-body-outset",
  preview=FALSE
)

#' R Option
source(file.path("C:","LlorR","scripts","lor_main.R" ))

# require(Hmisc)    # provides knitrSet and other functions
xaringanExtra::use_panelset()
```

```{r panelset-style}
xaringanExtra::style_panelset_tabs(font_family = "Roboto",
                                   active_foreground = "white",
                                   hover_foreground = "black",
                                   hover_border_color = "black",
                                   active_background = "#007fff"
                                   )
```

```{r raw-data}
# skip.dt <-fread(file.path("C:","LlorR","data","raw","skip_row.csv")  )
# skip.dt

#' load gameDT
#'############
file.DT <- file.path("C:","LlorR","data","raw","LoR_MatchDT.csv")
header        <- fread(file.DT, header = FALSE, na.strings = c("",NA), nrows = 1, stringsAsFactors = FALSE)
LoR.Match.RMD <- fread(file.DT, header = FALSE, na.strings = c("",NA), skip = params$skip )
colnames(LoR.Match.RMD) <- unlist(header,use.names = F)

#' load Games DT
#'##############
LoR.Match.RMD <- fread(file.path("C:","LlorR","data","raw","LoR_MatchDT.csv"), header = T, na.strings = c("", NA))

#' Read New Master
##################
LoR.Match.RMD <- fread(file.path("C:","LlorR","data","raw","LoR_TempDT.csv"), header = T, na.strings = c("",NA))

#' load Account
#'#############
LoR.Account.RMD <- fread(file.path("C:","LlorR","data","raw","LoR_ACCOUNT.csv"), header=T, na.strings = c("",NA), encoding = 'UTF-8') |>
  mutate( RiotID = glue::glue("{gameName}#{tagLine}"))

#' load DeckDT
#'############
LoR.Deck.RMD        <- fread(file.path("C:","LlorR","data","raw","LoR_DECK.csv"),na.strings = c("",NA))
```
```{r archetype-fix}
#' Limit the Deck DT to make the fixes much faster
deck_filter <- LoR.Match.RMD |>
  #' Base filters
  filter( game_type=="Ranked" ) |>
  filter( game_start_time_utc > as.POSIXct(params$start, tz = "UTC") ) |>
  select(deck_code_1,deck_code_2) |>
  pivot_longer( cols = contains("deck_code"),values_to = "decks" ) |>
  filter(decks!="") |>
  distinct(decks)

LoR.Deck.RMD <- LoR.Deck.RMD[deck_code %in% deck_filter$decks]

#' Archetype-Fix
#'##############
source(file.path("C:","LlorR","scripts","functions","lor_archetype_rmd.R"))
```

```{r prepare-data}
#' Metl tbl
#'#########
LoR.Melt.Matches.RMD <- LoR.Match.RMD |>
  filter( game_type=="Ranked" ) |>
  filter( game_start_time_utc > as.POSIXct(params$start, tz = "UTC") ) |>
  select( -ends_with("_3"),-ends_with("_4")  ) |>
  left_join(LoR.Deck.RMD[,.(deck_code,playerDeck_1=archetype)],  by=c("deck_code_1"="deck_code")) |>
  left_join(LoR.Deck.RMD[,.(deck_code,opponentDeck_1=archetype)],by=c("deck_code_2"="deck_code")) |>
  rename( playerPuuid_1 = puuid_1, playerPuuid_2 = puuid_2 ) |>
  mutate( playerDeck_2 = opponentDeck_1, opponentDeck_2 = playerDeck_1, opponentPuuid_1 = playerPuuid_2, opponentPuuid_2 = playerPuuid_1 ) |>
  pivot_longer(cols = c(ends_with("_1"),ends_with("_2")),
               names_to = c(".value"),
               names_pattern = "(.*)_[0-9]"
  ) |>
  #' finish 'process' data
  left_join(LoR.Account.RMD[,.(puuid,playerID=RiotID)]   ,by=c("playerPuuid"="puuid")) |>
  left_join(LoR.Account.RMD[,.(puuid,opponentID=RiotID)] ,by=c("opponentPuuid"="puuid")) |>
  left_join(LoR.Deck.RMD |> select(!archetype),by=c("deck_code","factions")) |>
  as.data.table()
```

```{r}
# MegaM0gwai
mogwai_puuid <- "q-xgjPYyTqlidh5YBzhE2CLX7WVJM8UuU_gf5GK1rARhIwZ0dx3PfYQV-wrpSZGVq1OllQelhNTzmA"

mogwai_games <- LoR.Melt.Matches.RMD |>
  filter( playerPuuid %in% mogwai_puuid ) |>
  filter( playerDeck == "Irelia/Miss Fortune" ) |>
  pull(match_key)

```


```{r}
 <- LoR.Melt.Matches.RMD |>
  filter( match_key %!in% mogwai_games) |>
  mutate( day = as.Date(game_start_time_utc), 
          isDeck = case_when(
            player == "Irelia/Miss Fortune" ~ "isDeck",
            TRUE ~ "Other"
          ) ) |>
  group_by( day ) |>
  count( isNasus ) |>
  pivot_wider( names_from = "isNasus",values_from = "n" ) |>
  dplyr::mutate( NasusThresh = replace_na(NasusThresh, 0)) |>
  mutate( pr = map2_dbl( .x = NasusThresh, .y = Other, ~.x/sum(.x,.y) ),
          pr_other = map_dbl( .x = pr , .f = ~1-.x ) )
  # mutate for second y-axis

  

ggplot( data = NT  ) +
  geom_line(data = NT, aes(x = day, y = NasusThresh)) +
  geom_line(data = NT, aes(x = day, y = pr*(max(NT$NasusThresh)/max(NT$pr)), color = "red") ) +
  geom_vline(xintercept = as.Date("2021-09-28"), linetype="dashed", 
                color = "red", size=0.5) +
  theme_539() +
  labs(
    title = "Games of Nasus/Thresh",
    subtitle = "number of games played since the release of Bandle",
    caption = element_markdown(glue::glue("Ranked games from {params$start} UTC to {params$end} UTC.
                                          Metadata of games collected with RiotGames API.
                                          Games from MegaMogwai are not included in the count.
                                          The dashed line is the day MegaMogwai released the Nasus/Thresh video.")),
    x = "Day",
    y = "#Games"
  ) +
  scale_color_manual( 
    name = element_blank(),
    values = c("red","black"),
    labels = c("<span style='color:red'>scaled playrate</span>","games")
    ) +
  theme(
    axis.text=element_text(size=10),
    axis.title=element_text(size=10,face="bold"),
    legend.background = element_blank(),
    legend.position = "top",
    legend.key = element_blank(),
    legend.key.width = unit(5,"pt"),
    legend.text = element_markdown(margin = margin())
    ) +
  guides(fill="none")
  
ggsave("./images/youtube-effect-MegaMogwai.png")
```

```{r plot,fig.width=12, fig.height=8}
# faint_puuid <- "BKsmyUbF8IOIVO4TWVB_5e22SinE3GPHeghb52UEy8h09qA_UckmRKQMkvG9BmrM4FZWPOzzSYzKDQ"
# majin_puuid <- "gYz6UL16RuVFu22GcFD9OYa11Oh7W-iKpCcOGsHg25cSbR_IyE0EONhrnB9nx3r0pPpAicA6PS27Mg"

deck <- "Irelia/Miss Fortune"
media.time <- as_datetime("2021-10-28 19:25:00", tz = "CET")

# MegaM0gwai
mogwai_puuid <- "q-xgjPYyTqlidh5YBzhE2CLX7WVJM8UuU_gf5GK1rARhIwZ0dx3PfYQV-wrpSZGVq1OllQelhNTzmA"
mogwai_games <- LoR.Melt.Matches.RMD |>
  filter( playerPuuid %in% mogwai_puuid ) |>
  filter( playerDeck == "Irelia/Miss Fortune" ) |>
  pull(match_key)

Deck <- LoR.Melt.Matches.RMD |>
  filter( match_key %!in% c(mogwai_games) ) |>
  mutate( time = floor_date(game_start_time_utc, unit="hour"),
          isDeck = case_when(
            playerDeck == deck ~ "Yes",
            TRUE ~ "No"
          ) ) |>
  group_by( time ) |>
  count( isDeck ) |>
  pivot_wider( names_from = "isDeck",values_from = "n" ) |>
  ungroup() |>
  mutate( Yes = replace_na(Yes, 0),
          cumYes = cumsum(Yes) )

ggplot( data = Deck  ) +
  geom_line(aes(x = time, y = cumYes)) +
  geom_vline(xintercept = media.time, linetype="dashed", color = "red", size=0.5) +
  # geom_vline(xintercept = as_datetime("2021-09-29 19:00:00"), linetype="dashed",  color = "red", size=0.5) +
  theme_539() +
  labs(
    title = glue::glue("The (Content) Creator (MegaMogwai) Effect"),
    subtitle = glue::glue("Games of {deck} - cumulative number of games played since Patch 2.18"),
    caption = element_markdown(glue::glue("Source: Metadata of games collected with RiotGames API. Ranked games from {params$start} UTC from players who reached Master last Season.
                                          Games from MegaMogwai are not included in the count. The dashed line is when MegaMogwai tweeted of the deck."
                                          )),
    x = "Time",
    y = "cumulative #Games"
  ) +
  theme(
    axis.text=element_text(size=12),
    axis.title=element_text(size=12,face="bold"),
    plot.caption = element_text(hjust = 0, face = "italic", size = 9)
    )
  
ggsave("./images/tweet-effect-Mog-IreliaMF.png", width = 12, height = 8)
```

```{r}
faint_puuid <- "BKsmyUbF8IOIVO4TWVB_5e22SinE3GPHeghb52UEy8h09qA_UckmRKQMkvG9BmrM4FZWPOzzSYzKDQ"
majin_puuid <- "gYz6UL16RuVFu22GcFD9OYa11Oh7W-iKpCcOGsHg25cSbR_IyE0EONhrnB9nx3r0pPpAicA6PS27Mg"

# deck <- "Sivir / Tristana (BC/SH)"
deck <- "Fizz / Lee Sin (BC/IO)"
Deck <- LoR.Melt.Matches.RMD |>
  filter( match_key %!in% c(faint_puuid,majin_puuid) & game_start_time_utc >= as.POSIXct("2021-09-10 00:00:00", tz = "UTC") ) |>
  arrange( game_start_time_utc ) |>
  mutate( isDeck = case_when(
            player == deck ~ 1,
            TRUE ~ 0
          ),
          PR = cumsum(isDeck)/row_number() ) |>
  select( game_start_time_utc, isDeck, PR )

ggplot( data = Deck  ) +
  geom_line(aes(x = game_start_time_utc, y = PR)) +
  # geom_vline(xintercept = as_datetime("2021-09-28 22:00:00"), linetype="dashed", 
  #               color = "red", size=0.5) +
  # geom_vline(xintercept = as_datetime("2021-09-29 19:00:00"), linetype="dashed", 
  #               color = "red", size=0.5) +
  theme_539() +
  labs(
    title = element_markdown(glue::glue("Games of {deck}")),
    subtitle = "cumulative number of games played since the release of Bandle",
    caption = element_markdown(glue::glue("Ranked games from {params$start} UTC to {params$end} UTC.
                                          Metadata of games collected with RiotGames API.
                                          Games from Faint and MajiinBae are excluded in the count.
                                          The first dashed line is once Dr.LoR tweeted of the deck.
                                          The second dashed line when Dr.LoR tweeted MajiinBae's results with the deck")),
    x = "Time",
    y = "cumulative #Games"
  ) +
  theme(
    axis.text=element_text(size=10),
    axis.title=element_text(size=10,face="bold")
    ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 0.01) )
  
# ggsave("./images/tweet-effect-SivirTristana.png")


LoR.Melt.Matches.RMD |>
  slice_head(n=2) |>
  jsonlite::write_json("prova.json")
```

```{r}

deck <- "Fizz / Lee Sin (BC/IO)"
Deck <- LoR.Melt.Matches.RMD |>
  mutate( time = floor_date(game_start_time_utc, unit="hour"),
          isDeck = case_when(
            player == deck ~ "Yes",
            TRUE ~ "No"
          ) ) |>
  group_by( time ) |>
  count( isDeck ) |>
  pivot_wider( names_from = "isDeck",values_from = "n" ) |>
  ungroup() |>
  mutate( Yes = replace_na(Yes, 0),
          cumYes = cumsum(Yes) )
  

ggplot( data = Deck  ) +
  geom_line(aes(x = time, y = cumYes)) +
  geom_vline(xintercept = as_datetime("2021-09-22 23:00:00"), linetype="dashed", 
                color = "red", size=0.5) +
  geom_vline(xintercept = as_datetime("2021-09-23 13:00:00"), linetype="dashed", 
                color = "red", size=0.5) +
  theme_539() +
  labs(
    title = "Games of Fizz/Lee",
    subtitle = "cumulative number of games played since the release of Bandle",
    caption = element_markdown(glue::glue("Ranked games from {params$start} UTC to {params$end} UTC.
                                          Metadata of games collected with RiotGames API.
                                          The first dashed line is once impetuosPandsa tweeted of the deck.
                                          The second dashed line when Yamato retweeted impetuosPandsa with his own results")),
    x = "Time",
    y = "cumulative #Games"
  ) +
  theme(
    axis.text=element_text(size=10),
    axis.title=element_text(size=10,face="bold")
    )
  
ggsave("./images/tweet-effect-LeeFizz.png")
```

