---
params:
  ind: "00"
  title: "From Curve to Cap"
  description: "Exploring Clustering Algorithms applied to Archetypes of Legends of Runeterra"
title: | 
  `r params$title`
description: |
  `r params$description`
# preview: 
base_url: https://www.llorr-stats.com
author:
  - name: Valentino (Legna) Vazzoler
date: 11-10-2021
output:
 distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
    self_contained: false
citation: false
bibliography: references.bib
draft: TRUE
---

CECACAIDFYAQEAQFAIAQECAPAMBAGBYIBECQCAQCBIAQEAYBAECAEBYCAEBAYOICAEBTMNYEAEAQGJABAMBAKAIEAMFAEAICEUXA
All from EU

CECQCAIDGUAQGAICAECACEQCAQBQEBAFAEAQGDQ7GAZQGAIBAM2ACBADBABACAI6HEAQEBABBIGA
LeYeti

- vS explained the concept of Skill-Cap by looking at the performances/win in the ladder by looking at the differences between Top Legends / DiamondI-IV
But differently for the Skill-Curve they don't look at the WR in function of games but at each MU-WR disparity ( which already big if it goes 2/3% )
They look at the single MU because the meta would easily influence the mean value ( and looking at what I have for PR between the two groups it is an obvious confounder)

Now, their example, Contact Rogue had a diff of 7.5% which is crazily high

So, now it's clearer why there is the problem I asked:
- Because a certain sample size is required also at top MMR  / in addition by taking the games from the start of the "top players" we know we can expect an higher WR because of the relationship between nGames and WR, but then, including games from when they were Plat+ seems wrong because of the definition

Podcast info: ep.62 ~28:00

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


