default:
  start_date: !expr lubridate::as_datetime("2023-03-01 10:00:00", tz = "US/Pacific") |> lubridate::with_tz("UTC")
  last_season: "S18"
  min_games: 10
  min_min_games: 20
  dim_grid: 15
  patch_name: "402"
  set_names: "Set06-06"
