---
params:
  ind: "03"
  title: "Defining Archetypes #3: A Clustering Analysis to a Season worth of Data"
  description: "Part2: Analysis and Results"
title: | 
  `r params$title`
description: |
  `r params$description`
# preview: 
base_url: https://www.llorr-stats.com
author:
  - name: Valentino (Legna) Vazzoler
date: 20-12-2021
output:
 distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
    self_contained: false
citation: false
# slug: legna2021archetype03
# bibliography: references.bib
draft: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = NA,
  R.options = list(width = 140,
                   digits.secs=6),
  dev.args = list(bg = 'transparent'), # make graphics with transparent background
  fig.align = 'center',
  fig.width=12,
  fig.height=8,
  engine.path = list(
    python = 'C:/anaconda/'   # -> use_python("C:/anaconda/")
  ),
  #'distill options
  layout="l-body-outset",
  preview=FALSE
)

#' R Option
options(scipen = 999)
source(file.path("C:","LlorR","scripts","lor_main.R" ))
xaringanExtra::use_panelset()

pacman::p_load(apcluster,dbscan,fpc,factoextra)
```

```{r panelset-style}
xaringanExtra::style_panelset_tabs(
  font_family = "Helvetica",
  active_foreground = "white",
  hover_foreground = "black",
  hover_border_color = "black",
  active_background = "#007fff"
  )
```
```{r read-example-03}
example_archetye_03 <- data.table::fread("C:/Users/Valentino Vazzoler/Documents/R/llorr-website/data/example_archetye_03.csv",na.strings = c("",NA))
# LoR.Deck.RMD       <- fread(file.path("C:","LlorR","data","raw","LoR_DECK.csv"),na.strings = c("",NA))
```

```{r monoDecks}
example_archetye_03 |>
  select(deck_code,archetype,allegiance,factions,cards.region.freq) |>
  separate_rows(factions,cards.region.freq) |>
  mutate(cards.region.freq = as.numeric(cards.region.freq) ) |>
  mutate(
    # unique 
    alle = map(allegiance, ~str_split(.x,pattern = ",")[[1]] ),
    alle = map(alle,unique),
    alle = map_chr(alle,~str_flatten(.x,collapse = ",")),
    alle.region = str_sub(alle,3,4)
  ) |>
  # either contain 33+ cards regions OR contain A SINGLE allegiance card
  filter(cards.region.freq >=  33 | (!is.na(allegiance) & !str_detect(alle,","))  ) |>
  # but since I separated the rows I have to take only the row with the correct region, the one of the allegiance card since I then have to count the cards of the region of the Allegiance card
  filter(is.na(alle.region) | alle.region==factions) |>
  as.data.table() -> mono.deck.DT

# mono.deck.DT |>
#   tabyl(allegiance,factions)
```

# Analysis

```{r monoIonia, fig.width=12, fig.height=8}
# which decks are "mono region" with Ionia?
deck.IO <- mono.deck.DT[factions == "IO", deck_code]

# "sparse matrix" of deck's cards
sparse.IO <- sparseMatrix(deck.IO,source = example_archetye_03)
# SIMILARITY MATRIX
Dsim.IO   <- eisen_cos.sim(sparse.IO,dist = F)

set.seed(123)
ap.IO <- apcluster(as.matrix(Dsim.IO),details = T)
apcluster::heatmap(ap.IO,as.matrix(Dsim.IO), cexRow= 0, cexCol = 0, legend = "col" )
```


```{r monoIonia, fig.width=12, fig.height=8}
dend.IO <- hclust(as.dist(1 - Dsim.IO),method = "average")
plot(dend.IO)
```

```{r}
# table(example_archetye_03[deck_code %in% deck.IO, archetype],ap.IO@idx) |>
#   as.data.table() |>
#   pivot_wider(names_from = "V2",values_from = "N") |>
#   arrange(desc(`62`),desc(`66`),desc(`67`))
```

```{r noxus-pnz}
# which decks are "mono region" with Noxus PnZ?
deck.NXPZ <- example_archetye_03[factions == "NX,PZ", deck_code]

# "sparse matrix" of deck's cards
sparse.NXPZ <- sparseMatrix(deck.NXPZ,source = LoR.Deck.RMD)
# SIMILARITY MATRIX
Dsim.NXPZ   <- eisen_cos.sim(sparse.NXPZ,dist = F)

set.seed(123)
ap.NXPZ <- apcluster(as.matrix(Dsim.NXPZ),details = T)
apcluster::heatmap(ap.NXPZ,as.matrix(Dsim.NXPZ), cexRow= 0, cexCol = 0, legend = "col" )
```


```{r noxus-pnz}
dend.NXPZ <- hclust(as.dist(1 - Dsim.NXPZ),method = "average")
plot(dend.NXPZ)
```


```{r noxus-pnz}
table(example_archetye_03[deck_code %in% deck.NXPZ, archetype],ap.NXPZ@idx) |>
  as.data.table() |>
  pivot_wider(names_from = V2,values_from = "N", names_glue = "{.value}_{V2}") |>
  arrange(across(starts_with("N_"),desc)) -> tbl.NXPZ

tbl.NXPZ |>
  relocate(1,sort(unlist(tbl.NXPZ[1,-1],use.names = F),decreasing = T, index.return = T)$ix+1) |>
  arrange(across(starts_with("N_"),desc))
```

```{r}
# set.seed(123)
# dbscan::kNNdistplot(as.dist(1 - Dsim.NXPZ), k =  1)
# abline(h = 0.2775, lty = 2, col = "red")

set.seed(123)
res.NXPZ.Drisoth.min1 <- dbscan::dbscan(dist(sparse.NXPZ, method = "manhattan", diag = FALSE, upper = FALSE), 37, 1)
set.seed(123)
res.NXPZ.Drisoth.min2 <- dbscan::dbscan(dist(sparse.NXPZ, method = "manhattan", diag = FALSE, upper = FALSE), 37, 2)

set.seed(123)
res.NXPZ.Drisoth <- dbscan::dbscan(dist(sparse.NXPZ, method = "manhattan", diag = FALSE, upper = FALSE), 37, 20)

res.NXPZ.Drisoth.min1$cluster
res.NXPZ.Drisoth.min2$cluster

which(res.NXPZ.Drisoth.min2$cluster==0)

example_archetye_03[deck_code %in% deck.NXPZ, ][ which(res.NXPZ.Drisoth.min2$cluster==0) ]



table(
  example_archetye_03[deck_code %in% deck.NXPZ, archetype],
  res.NXPZ.Drisoth$cluster
)
```


```{r}
set.seed(123)
w <- sample(x = c(1:1000),size = 1467,replace = T )
set.seed(123)
res.IO.Drisoth.min2 <- dbscan::dbscan(dist(sparse.IO, method = "manhattan", diag = FALSE, upper = FALSE), 37, 5 , weights = w )

res.IO.Drisoth <- dbscan::dbscan(dist(sparse.IO, method = "manhattan", diag = FALSE, upper = FALSE), 37, 1 )



example_archetye_03[deck_code %in% deck.IO, ][ which(res.IO.Drisoth.min2$cluster==0) ]

example_archetye_03[deck_code %in% deck.IO, ][ which(res.IO.Drisoth$cluster!=1) ]
```