---
params:
  ind: "04"
  title: "Defining Archetypes #4: Approaching a Clustering Analysis with a Season worth of Data"
  description: "Describing the basic issues when using Clustering Analysis with a bigger dataset and a possible solution in the context of Legends of Runeterra decks."
title: | 
  `r params$title`
description: |
  `r params$description`
base_url: https://www.llorr-stats.com
author:
  - name: Valentino (Legna) Vazzoler
date: 12-25-2021
output:
 distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
    self_contained: false
citation: false
slug: legna2021archetype03
draft: FALSE
# bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  error   = FALSE,
  message = FALSE,
  comment = NA,
  R.options = list(width = 140,digits.secs=6),
  dev.args  = list(bg = 'transparent'),
  fig.align = 'center',
  fig.width = 12,
  fig.height= 8,
  layout="l-body-outset"
  # preview=FALSE,
  # engine.path = list(python = 'C:/anaconda/')
)

options(scipen = 999)
source(file.path("C:","LlorR","scripts","lor_main.R" ))
source(file.path("C:","LlorR","scripts","functions","lor_constants.R"))
source(file.path("C:","LlorR","scripts","functions","lor_functions.R"))

xaringanExtra::use_panelset()
```

```{r style}
xaringanExtra::style_panelset_tabs(
  font_family = "Helvetica",
  active_foreground = "white",
  hover_foreground = "black",
  hover_border_color = "black",
  active_background = "#007fff")

table_nums  <- captioner::captioner(prefix = "Tab.")
figure_nums <- captioner::captioner(prefix = "Fig.")

f.ref <- function(x) {
  stringr::str_extract(table_nums(x), "[^:]*")
}
```

# Introduction

```{r load-data}
example_archetye_03 <- data.table::fread("C:/Users/Valentino Vazzoler/Documents/R/llorr-website/data/example_archetye_03.csv",na.strings = c("",NA))
```

```{r}
example_archetye_03 |>
  mutate(cards.region = if_else(!is.na(cards.region.fix), cards.region.fix, cards.region ) )  |>
  mutate(
    alle = map(allegiance, ~str_split(.x,pattern = ",")[[1]] ),
    alle = map(alle,unique),
    alle = map_chr(alle,~str_flatten(.x,collapse = ",")),
  ) |>
  filter(!str_detect(alle,",") | is.na(alle)) |>  # 7 decks with double Allegiance
  mutate( alle.region = str_sub(alle,3,4) ) |>
  separate_rows(cards.region,cards.region.freq, sep = ",",convert = T ) |>
  # take the part with more cards
  group_by(deck_code) |>
  slice_max(cards.region.freq,n=1,with_ties = T) |>
  ungroup() |>
  filter(cards.region.freq > 32 | alle.region==cards.region) -> MonoDeckDT
```



