---
title: "THE TESTING META REPORT NAME IS TOO LONG, IT IS EVEN LONGER!!!"
description: |
  Quick testing page for CSS / Format / Functions and other stuff.
base_url: https://llorr-stats.netlify.app
preview:   
author:
  - name: Valentino (Legna) Vazzoler
date: 12-06-1986
output:
 distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 2
    self_contained: false
citation: false
draft: true
twitter:
  site: "@Maou_Legna"
  creator: "@Maou_Legna"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = NA,
  R.options = list(width = 140,
                   digits.secs=6),
  dev.args = list(bg = 'transparent'), # make graphics with transparent background
  fig.align = 'center',
  fig.width=9,
  fig.height=6,
  engine.path = list(
    python = 'C:/anaconda/'   # -> use_python("C:/anaconda/")
  ),
  #'distill options
  layout="l-body-outset",
  preview=FALSE
)

#' R Option
source(file.path("C:","LlorR","scripts","lor_main.R" ))

# require(Hmisc)    # provides knitrSet and other functions
xaringanExtra::use_panelset()
#' Python
py_run_string("print('Hello World')")
lor_deckcodes <- import("lor_deckcodes")
py_module_available("lor_deckcodes")
```

```{r panelset-style}
xaringanExtra::style_panelset_tabs(font_family = "Roboto",
                                   active_foreground = "white",
                                   hover_foreground = "black",
                                   hover_border_color = "black",
                                   active_background = "#007fff"
                                   )
```

```{r raw-data}
#' load Account
#'#############
file.Account <- file.path("C:","LlorR","data","raw","LoR_ACCOUNT.csv")
LoR.Account.RMD <- fread(file.Account, header=T, na.strings = c("",NA), encoding = 'UTF-8') %>%
  mutate( RiotID = paste(gameName,tagLine),refID = puuid_4 ) %>%
  pivot_longer(
  cols = c("puuid_1","puuid_2","puuid_3","puuid_4"),
  names_to = "origin",
  values_to = "puuid"
)

#' load DeckDT
#'############
LoR.Deck        <- fread(file.path("C:","LlorR","data","raw","LoR_DECK.csv"),na.strings = c("",NA))

#' load gameDT
#'############
file.DT <- file.path("C:","LlorR","data","raw","LoR_MatchDT.csv")
# header        <- fread(file.DT, header = FALSE, na.strings = c("",NA), nrows = 1, stringsAsFactors = FALSE)
LoR.Match.RMD <- fread(file.DT, header = T, na.strings = c("", NA))
```

```{r prepare-data}
LoR.Melt.Matches.RMD <- LoR.Match.RMD %>%
  #' Base filters
  filter( game_type=="Ranked" ) %>%
  # filter( game_start_time_utc >= as.POSIXct(params$prev, tz = "UTC") & game_start_time_utc < as.POSIXct(params$start, tz = "UTC") ) %>%
  #' 'process' data
  left_join(.,LoR.Deck[,.(deck_code,archetype)] %>% setnames(old = "archetype", new = "player_1")   ,by=c("deck_code_1"="deck_code")) %>%
  left_join(.,LoR.Deck[,.(deck_code,archetype)] %>% setnames(old = "archetype", new = "opponent_1") ,by=c("deck_code_2"="deck_code")) %>%
  mutate( player_2 = opponent_1, opponent_2 = player_1, oppoppuid_1 = puuid_2, oppoppuid_2 = puuid_1 ) %>%
  select( match_key,server,game_start_time_utc,game_version,total_turn_count,
          ends_with("_1"),ends_with("_2"),-ends_with("_3"),-ends_with("_4"),-contains("deck_id"),-contains("participants") ) %>%
  #' melt data
  melt(id.vars=c("match_key","server","game_start_time_utc","game_version","total_turn_count"), measure.vars=patterns(
    str_sub(
      names(select(.,ends_with("_1")))
      ,end = -3)
  ),
  value.name = str_sub(
    names(select(.,ends_with("_1")))
    ,end = -3)
  ) %>%
  #' finish 'process' data
  left_join(. , LoR.Account.RMD[,c("puuid","RiotID","refID")] %>% setnames(old = "RiotID", new = "userID")     ,by=c("puuid"="puuid")) %>%
  left_join(. , LoR.Account.RMD[,c("puuid","RiotID")] %>% setnames(old = "RiotID", new = "opponentID") ,by=c("oppoppuid"="puuid")) %>%
  # left_join(.,LoR.Deck %>% select(!archetype),by=c("deck_code","factions")) %>%
  select(-ends_with("puuid"),-refID)
```

# section
::: l-page

::::: {.panelset}

::: {.panel}

## Time Series Highlist {.panel-name}

Wow, funziona per bene!

```{r champion-freq-by-date}
m = 10

start = as.POSIXct("2021-07-21 21:00:00", tz = "UTC")
end   = as.POSIXct("2021-07-21 21:00:00", tz = "UTC") + days(7)

Champion.deck.daily <- (LoR.Ranked.RMD %>%
  dplyr::filter( game_start_time_utc >= {{start}} & game_start_time_utc < {{end}} ) %>%
  rename(.,"champions"="player") %>%
  arrange(game_start_time_utc) %>%
  select(game_start_time_utc,champions) %>%
  mutate( num_cc = factor(champions) %>% as.numeric() ))[ , cumFreq := (cumsum(num_cc)/num_cc)/.I , by=champions ] %>%
  select(!num_cc) %>%
  mutate( champions = factor(champions) %>% fct_infreq() )

fct_values <- LoR.Ranked.RMD %>%
 dplyr::filter( game_start_time_utc >= {{start}} & game_start_time_utc < {{end}} ) %>%
 # mutate( top5 = fct_lump(champions, n = m, w = tot, ties.method = "max") ) %>%
 mutate( top5 = fct_lump_n(player,n = m) %>% fct_infreq() ) %>%
 pull(top5) %>% levels()
```

```{r}
# # This theme extends the 'theme_minimal' that comes with ggplot2.
# # The "Lato" font is used as the base font. This is similar
# # to the original font in Cedric's work, Avenir Next Condensed.
# theme_set(theme_minimal(base_family = "Lato"))
# 
# 
# theme_update(
#   # Remove title for both x and y axes
#   axis.title = element_blank(),
#   # Axes labels are grey
#   axis.text = element_text(color = "grey40"),
#   # The size of the axes labels are different for x and y.
#   # axis.text.x = element_text(size = 20, margin = margin(t = 5)), # **A**
#   # axis.text.y = element_text(size = 17, margin = margin(r = 5)), # **A**
#   # Also, the ticks have a very light grey color
#   axis.ticks = element_line(color = "grey91", size = .5),
#   # The length of the axis ticks is increased.
#   axis.ticks.length.x = unit(1.3, "lines"),
#   axis.ticks.length.y = unit(.7, "lines"),
#   # Remove the grid lines that come with ggplot2 plots by default
#   panel.grid = element_blank(),
#   # Customize margin values (top, right, bottom, left)
#   plot.margin = margin(20, 40, 20, 40),
#   # Use a light grey color for the background of both the plot and the panel
#   plot.background = element_rect(fill = "grey98", color = "grey98"),
#   panel.background = element_rect(fill = "grey98", color = "grey98"),
#   # Customize title appearence
#   plot.title = element_text(
#     color = "grey10", 
#     # size = 28, 
#     face = "bold",
#     margin = margin(t = 15)
#   ),
#   # Customize subtitle appearence
#   plot.subtitle = element_markdown(
#     color = "grey30", 
#     size = 16,
#     lineheight = 1.35,
#     margin = margin(t = 15, b = 40)
#   ),
#   # Title and caption are going to be aligned
#   plot.title.position = "plot",
#   plot.caption.position = "plot",
#   plot.caption = element_text(
#     color = "grey30", 
#     # size = 13,
#     lineheight = 1.2, 
#     hjust = 0,
#     margin = margin(t = 40) # Large margin on the top of the caption.
#   ),
#   # Remove legend
#   legend.position = "none"
# )
```

```{r plot-date-by-date}
meta_evo <- ggplot(
   # The ggplot object has associated the data for the highlighted countries
  data = Champion.deck.daily %>% filter(champions %in% fct_values[-1]),
  aes(game_start_time_utc, cumFreq, group = champions)
  ) +
  ## Lines for the non-highlighted countries
  geom_line(
    data = Champion.deck.daily %>% filter(champions %!in% fct_values[-1]),
    color = "grey75",
    size = .6,
    alpha = .5
  ) +
  ## Lines for the highlighted countries.
  # It's important to put them after the grey lines
  # so the colored ones are on top
  geom_line(
    aes(color = champions),
    size = .9
  ) +
  # geom_text(aes(label=champions,color = champions))
  geom_text_repel(
    data = Champion.deck.daily %>% filter(champions %in% fct_values[-1]) %>% group_by(champions) %>% slice_max(game_start_time_utc,n=1),
    aes(label=str_to_upper(champions),color = champions),
    # aes(color = champions, label = champions),
    family = "Lato",
    fontface = "bold",
    size = 3,
    direction = "y",
    xlim = c(as.POSIXct(max(Champion.deck.daily$game_start_time_utc) + hours(12)), NA),
    force = 3,
    hjust = 1,
    segment.size = .7,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 15
  ) +
  scale_x_datetime(
    # expand = c(0.02,0.01),
    date_minor_breaks = "1 day",
    limits = c(as.POSIXct("2021-07-21 21:00:00", tz="UTC"), as.POSIXct("2021-07-28 21:00:00", tz="UTC")+hours(24))
    # limits = c(as.POSIXct(params$start, tz="UTC"), as.POSIXct(params$end, tz="UTC"))
  )  +
  scale_y_continuous(
    expand = c(0, 0),
    limits = c(0,0.20),
    breaks = seq(0,0.20,0.02),
    labels = scales::percent_format(accuracy = 1) # glue::glue("{format(seq(0, 0.20, by = 0.05), nsmall = 2)}%")
  ) +
  scale_color_manual(
    values = c(rcartocolor::carto_pal(n = 10, name = "Vivid")[1:10-1], "grey50")
  ) +
  labs(x = "Date",
       y = "Percent",
       title = "Evolution of Play Rate over time"
       # caption = glue::glue("Data from Riot API • Ranked games from Master players • ... ")
  ) +
  # tab_footnote(
  #   footnote = md(glue::glue("Max datetime recovered: {max_time} UTC from {params$start} to {params$end} UTC" )),
  #      ) + 
  theme_bw() +
  theme(
    plot.title    = element_text(face = "bold", size = 15),
    axis.title.x  = element_text(face = "bold", size = 12),
    axis.title.y  = element_text(face = "bold", size = 12),
    axis.text.x   = element_text(size = 8),
    legend.position = "none"
  )

meta_evo
```
:::

::: {.panel}

## History {.panel-name}

```{r}
calendar <- tibble(start = seq(as.POSIXct("2020-04-29 21:00:00", tz = "UTC"),Sys.time(), by = "7 DSTdays"),
                   end   = start + days(7),
                   index = seq_len(length(start)),
                   label = glue("Week {index}")
                   )

region.freq.history  <- map2_df( .x = calendar$start, .y = calendar$end, ~get_factions_freq(x = LoR.Melt.Matches.RMD, start = .x ,end = .y,format = "long" )   )
weekly.patch.history <- map2_chr( .x = calendar$start, .y = calendar$end, ~get_patch_main(x = LoR.Melt.Matches.RMD, start = .x ,end = .y )   )
# 
region.history <- cbind(
calendar,
weekly.patch.history,
region.freq.history
) %>%
  rename("patch"="weekly.patch.history") %>%
  rowwise() %>%
  mutate(total = sum(c_across(contains("_n")) ) ) %>%
  group_by(patch) %>%
  mutate(week.patch.index = row_number() ) %>%
  mutate( patch_lbl = case_when(
          !is.na(patch) == T ~ glue("{patch} - Week {week.patch.index}"),
          TRUE ~ patch
          )
  ) %>%
  add_column( sample_size = map2_dbl(.x = calendar$start, .y = calendar$end, .f = ~NROW( LoR.Match.RMD %>% 
                                                            dplyr::filter( game_start_time_utc >= as.POSIXct(.x, tz = "UTC") & game_start_time_utc < as.POSIXct(.y, tz = "UTC") & game_type == "Ranked" )
                                                          ) ) ) %>%
  rowwise() %>%
  mutate(gini = DescTools::Gini( c_across(contains("_freq")),na.rm = T ))

# LoR.Match.RMD %>%
#   dplyr::filter( game_start_time_utc >= as.POSIXct("2021-07-21 21:00:00", tz = "UTC") & game_start_time_utc < as.POSIXct("2021-07-28 21:00:00", tz = "UTC"))

fwrite(region.history,file.path("C:","LlorR","data","clean","Factions_History.csv"))
region.history <- fread(file.path("C:","LlorR","data","clean","Factions_History.csv"))
```

```{r format-region}
region.formatted <- region.history %>%
  filter(index %in% 46:NROW(region.history) ) %>%
  # slice_tail(n = 2) %>%
  pivot_longer(
    cols = "Bilgewater_freq":"Shurima_freq",
    names_to = "region",
    values_to = "freq"
  ) %>%
  select(index,label,patch,patch_lbl,region,freq,sample_size,gini) %>%
  group_by(label) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = rank(-freq),
         region_lbl = str_remove(region,pattern = "_freq" ) 
         ) 
  

region.formatted
 
```

```{r static-plots}
staticplot = ggplot(region.formatted , aes(rank, group = region, 
                fill = as.factor(region), color = as.factor(region))) +
  geom_tile(aes(y = freq/2,
                height = freq,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(region_lbl, " ")), vjust = 0.2, hjust = 1 ,color="black") +
  geom_label(aes(x = 8, y = 0.25, label = glue("Sample Size: {sample_size} \n Gini Index: {gini %>% round(.,3)}" )), size=3, vjust = 0.2, hjust = 1 ,color="black", fill="grey85") +
  # geom_text(aes(y=freq,label = freq %>% scales::percent(accuracy = 0.1) , hjust=0)) +
  geom_label(aes(y=freq,label = freq %>% scales::percent(accuracy = 0.1)), fill="white",color="black" )  +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_reverse() +
  scale_fill_manual("legend", values = list.levels$colorRegion.Balco) +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        # axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        # plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 4, "cm")
       ) +
    scale_colour_manual(values = list.levels$colorRegion.Balco) +
    scale_y_continuous(limits = c(0, 0.30),
                     breaks = seq(0, 0.30,0.05),
                     labels = scales::percent_format(accuracy = 1) )

staticplot  
```

```{r}
require(gganimate)
anim = staticplot + transition_states(patch_lbl, transition_length = 1, state_length = 1) +
  # view_follow(fixed_x = TRUE)  +
  labs(title = 'Region Play Rate: {closest_state}',  
       subtitle  =  "by Inclusion Rate",
       caption  = "The Gini index is a measure of heterogeneity and in this case it described how similar are the play rate among the region. It's normalized in (0,1) and it's equal to 1 if a single region had 100% play rate while it would be 0 is all regions had the same play rate."
       )
# anim
```
```{r}
# For GIF
animate(anim, 200, fps = 20,  width = 600, height = 500, 
        renderer = gifski_renderer("images/region-from-2_4.gif"))
```
:::::

:::



